### PR TITLE
Change default token type from "token" to "access"

### PR DESCRIPTION
**Pull request by hassox**

### CODE REVIEW

**Comment by doomspork** [comment]
@hassox this looks good, what's the rationale behind this change?

**Comment by hassox** [comment]
The 'token' type is pretty useless. Whenever we talk about token types (taking a nod from OAuth) we usually talk about access vs refresh tokens etc. I thought it'd be better to use 'access' as the typ so it means something.

**Comment by doomspork** [comment]
Sounds good @hassox, thanks! 👍

**Comment by doomspork** [comment]
@hassox do you want to merge this before we release a new version for #169?

**Comment by dustinfarris** [comment]
Is this actually used anywhere?

**Comment by doomspork** [comment]
@dustinfarris this is not yet used

**Comment by doomspork** [comment]
@hassox can I merge this guy in for the new release?

**Pull request merged**
