### PR TITLE
move plug permisions to plugs

### PR DESCRIPTION
**Pull request by Hanspagh**
Proposed fix to #415. I have moved the permission logic together with the other plugs, since `Code.ensure_loaded ` only seem to work on module level on compile time. I had to move the plug logic into a separate module. This however is a breaking change since plug permissions are no longer available in the module `Guardian.Permissions.Bitwise`

### CODE REVIEW

**Comment by hassox** [comment]
This was addressed in https://github.com/ueberauth/guardian/pull/404 but has not yet been released.

I've built against the master branch without plug and without running into this issue.

Can you please confirm that this is still an issue on master?

**Comment by Hanspagh** [comment]
It works, I build from 1.0-beta before but that didn't include #404.

**Comment by hassox** [comment]
Thanks for the PR and confirmation. I will try and get an updated release out tomorrow.

**Comment by Hanspagh** [comment]
Do you track who is working on fixing what issues, should I wouldn't end up trying to fix something that is already fixed :)

**Comment by hassox** [comment]
Unfortunately we don't have a solid way of doing this atm. We know when folks are working on a fix when a PR comes up - but unfortunately this PR didn't close out the bug. 

I'd love to chat about ways we might handle this moving forward in slack #ueberauth. @doomspork will likely have some solid ideas on it also.

**Pull request closed without merging**
