### PR TITLE
Mix format setup

### PR DESCRIPTION
**Pull request by pedroassumpcao**
This PR sets up mix format and run it across all files.

### CODE REVIEW

**Comment by yordis** [comment]
@pedroassumpcao I think this https://github.com/ueberauth/guardian/pull/454 is doing the same

**Comment by pedroassumpcao** [comment]
@yordis yes, I saw it later, mine has the mix format config that maybe can be added to #454. I can close this, let me know.

**Comment by yordis** [comment]
@ueberauth/core ^

@pedroassumpcao no sure, leave it open and we close it if we do not use it.

In any case, thanks a lot for your support!

**Comment by hassox** [comment]
Lets merge this one

**Pull request merged**
