### PR TITLE
Support {:system, VAR_NAME} in config

### LINKED ISSUE #219: Support {:system, VAR_NAME} idiom for secret_key
It's a pretty common standard to support such a value in config for things that should be loaded from the environment. Secrets and seed values to algorithms are a common thing.

If you agree this would be useful, I can work on this.

### PR DESCRIPTION
**Pull request by michalmuskala**
Closes #219

### CODE REVIEW

**Comment by michalmuskala** [comment]
The failure seems to be cause by credo bug, that refuses to accept code such as:
```elixir
foo() |> bar()
```
The update of credo fixes the issue according to my tests.

**Comment by doomspork** [comment]
@hassox any thoughts on this before I merge?

**Comment by hassox** [comment]
The code looks just fine to me. Travis is erroring though.

**Comment by michalmuskala** [comment]
@hassox yes, travis errors, because credo doesn't like that line https://github.com/ueberauth/guardian/pull/220/files#diff-98bc41bc6745bf48898940055a7dfb7aR276
It looks like a bug, in the credo version that guardian currently uses. Upgrading it fixes this.

**Comment by doomspork** [comment]
@michalmuskala could you bump the credo version so the build passes?

**Comment by michalmuskala** [comment]
@doomspork updated

**Comment by doomspork** [comment]
Thank you @michalmuskala!

**Pull request merged**
