### PR TITLE
[#435] Fix keep method call on revoke

### PR DESCRIPTION
**Pull request by SofaKing18**
Hello, I hope I made the right decision, not a Kludge

### CODE REVIEW

**Comment by yordis** [comment]
@SofaKing18 this was fixed by https://github.com/ueberauth/guardian/pull/430

**Comment by SofaKing18** [comment]
@yordis 
variable mod is not set => nil.peek(token) raises error
https://github.com/ueberauth/guardian/blob/21622bf30328ef92750dcc5459829016ea4cb93d/lib/guardian.ex#L664

**Comment by yordis** [comment]
@SofaKing18 could you use the `master` branch and verify the error please? This line https://github.com/ueberauth/guardian/blob/2b486689c4605b982951ae56f5a09db1d94b422c/lib/guardian.ex#L393 should fix your issue because you shouldn't be calling directly `.peek` from the module but from Guardian module.

And if the error continues, then could you add unit testing as well so it covers this issue.

**Comment by SofaKing18** [comment]
Error is not actual for master branch, waiting for new release, please :)

**Comment by yordis** [comment]
@ueberauth/core @hassox do you think is possible to get a release for this? Many people that will no setup the module will get this error ...

**Pull request closed without merging**
