### PR TITLE
Add OTP 20 to Travis matrix

### PR DESCRIPTION
**Pull request by samhamilton**

### CODE REVIEW

**Comment by doomspork** [comment]
Thanks @samhamilton!  Do we want to allow failures on OTP 20 via the `allow_failures` option?  As I understand it there's not complete support for it as-of yet with Elixir.

**Comment by odarriba** [comment]
hey!

There is support for it on 1.4.5 and 1.5.0-rc0 (which I don't know if are being tested).
Also, I think it should work pretty well with 1.4 versions for most software 🤔

**Comment by doomspork** [comment]
Great, thanks for the heads up @odarriba!  @hassox do you have any problems with merging this?

**Comment by scrogson** [comment]
I'm confused...isn't this change already in `master`? #347 

Am I blind? I don't see any difference.

**Comment by samhamilton** [comment]
sorry! I didn't spot that.

**Pull request closed without merging**
