### PR TITLE
Update Jose to support OTP24 

### PR DESCRIPTION
**Pull request by drumusician**
In are moving our apps to OTP24 / Elixir 1.12 and as guardian is still using an outdated Jose version, we were unable to upgrade due to the a deprecated function:
```
Warning: crypto:hmac/3 is deprecated and will be removed in OTP 24; use use crypto:mac/4 instead
```

This PR updates Jose and also updates 1 function that Guardian uses from Jose that has also changed.

These seemed to have worked for our apps, but I am really not sure if it is this simple. I wanted to push this back to you guys so you can check if this is as simple as updating this or if it is more involved than that.

Looking forward to what you guys think. In the meantime I'll use my fork to test our apps with these changes. If I do encounter any issues, I'll be sure to flag them here as well.

### CODE REVIEW

**Review by yordis — APPROVED** [review]

**Comment by yordis** [comment]
🚀

**Comment by eriklindgren** [comment]
A new release with this would be awesome, it's currently preventing us too from upgrading to OTP 24. Thanks for all your hard work!

**Comment by atomkirk** [comment]
Is this lib abandoned? A release would be great. any workarounds?

**Comment by eriklindgren** [comment]
@atomkirk the updated version has actually been released: https://hex.pm/packages/guardian/2.2.0

**Comment by atomkirk** [comment]
Oh, any idea why its not updated here

https://github.com/ueberauth/guardian/releases

**Comment by yordis** [comment]
@atomkirk we were using `tag` instead of `releases` to kick the release pipeline, I fixed that here: https://github.com/ueberauth/guardian/pull/684

Which will make sure people use Releases instead of tags, sorry for the confusion, trying to clean up little by little.

**Pull request merged**
