### PR TITLE
578 Fix error message

### PR DESCRIPTION
**Pull request by yordis**

### CODE REVIEW

**Comment by doomspork** [comment]
@yordis looks good, you need to rebase 👍

**Comment by yordis** [comment]
@doomspork now I remember why I didn't finish with this ticket.

For what it happening right now, it seems that previous tests weren't actually working as expected, there were all failing about the claim but since the expectations were generic we didn't cut it.

Can you confirm this?

**Comment by doomspork** [comment]
@yordis it appears to be a formatter issues on Travis:

```shell
** (Mix) mix format failed due to --check-formatted.
The following files were not formatted:
  * /home/travis/build/ueberauth/guardian/test/guardian/permissions/permissions_test.exs
make: *** [testing] Error 1
The command "make testing" exited with 2.
```

**Comment by yordis** [comment]
Sorry, I forgot to push the formatted version.

**Comment by doomspork** [comment]
Closing in favor of #590

**Pull request closed without merging**
