### PR TITLE
Improve travis setup

### PR DESCRIPTION
**Pull request by yordis**
@ueberauth/developers I am still working on it.

### CODE REVIEW

**Comment by doomspork** [comment]
@yordis I'm open to dropping the other versions for Travis.  @hassox thoughts?

**Comment by hassox** [comment]
Always down for dropping old versions personally ;)

**Comment by yordis** [comment]
@ueberauth/core yeah I wouldn't train the folks that it is fine for them to do not do their job upgrading their platform and by so we carry on their responsibilities

**Comment by yordis** [comment]
@ueberauth/core done!

**Pull request merged**
