### PR TITLE
fix pattern miss match when use with GuardianDB

### PR DESCRIPTION
**Pull request by yuchunc**
Module Guardian line 105, changed `:ok` to `{:ok, _}`

### CODE REVIEW

**Comment by yuchunc** [comment]
#242

**Comment by faywong** [comment]
This issue has blocked me(freshman to elixir) for two days before i almost give up the guardian db solution.

Anyway, thanks for google & all your efforts. 
In which release will this bugfix will be included?

**Comment by yuchunc** [comment]
I would suggest you rolling back to an earlier version of Guardian. Since I am not the maintainer, I have no ETA on when thhis might get merged.

Also, if you are just trying to run development, you could just go into `/deps` change Guardian's code, then removed the Guardian directory under `/_build`. It will recompile your change, this was how I was sure this was a library issue.

Hope that helps. :)

**Comment by doomspork** [comment]
Thank you @yuchunc, @faywong I'll be releasing a new version this week.  For the time being you can use:

```ruby
{:guardian, github: "ueberauth/guardian"}`
```

**Comment by collegeimprovements** [comment]
I'm getting the same error with the new version also.

**Comment by doomspork** [comment]
Thanks for the report @collegeimprovements 👍

**Pull request merged**
