### PR TITLE
fix ttl issue

### LINKED ISSUE #153: Setting TTL with encode_and_sign
Hello!

  I'm trying to generate a token with non-default TTL.

``` elixir
iex(1)> alias App.{Repo, Device, DeviceRegistration.Monitor}
[nil, nil, nil]
iex(2)> device = Repo.get_by(Device, id: "db749ee8-1e9f-11e6-9d47-4b5e65de4b92")
[debug] QUERY OK db=2.9ms decode=0.2ms queue=0.2ms
SELECT d0."id", d0."is_enabled", d0."user_id", d0."inserted_at", d0."updated_at" FROM "devices" AS d0 WHERE (d0."id" = $1) [<<219, 116, 158, 232, 30, 159, 17, 230, 157, 71, 75, 94, 101, 222, 75, 146>>]
%App.Device{__meta__: #Ecto.Schema.Metadata<:loaded>,
 id: "db749ee8-1e9f-11e6-9d47-4b5e65de4b92",
 inserted_at: #Ecto.DateTime<2016-05-20 15:31:01>, is_enabled: true,
 updated_at: #Ecto.DateTime<2016-05-20 15:31:01>,
 user: #Ecto.Association.NotLoaded<association :user is not loaded>,
 user_id: nil}
iex(3)> ttl = Application.get_env(:app, :reg_ttl)
{30, :minutes}
iex(4)> claims = Guardian.Claims.app_claims |> Guardian.Claims.ttl(ttl)
%{"exp" => 1463768778, "iat" => 1463766978, "iss" => "StreamTo.TV",
  "jti" => "7dc915a5-ff0b-4d41-bc1b-b19804550897"}
iex(5)> exp_at = claims["exp"]
1463768778
iex(6)> %{code: code, exp: old_exp_at} = Monitor.device_added(device.id, exp_at)
%{code: "LCBZH6WW", exp: 1463768716}
iex(7)> ttl = {old_exp_at - :os.system_time(:seconds) - 1, :seconds}
{1709, :seconds}
iex(8)> claims = Guardian.Claims.app_claims |> Guardian.Claims.ttl(ttl)
%{"exp" => 1463768725, "iat" => 1463767016, "iss" => "StreamTo.TV",
  "jti" => "294a5c14-f5e4-4b57-9f30-e6551825ccaf"}
iex(9)> {:ok, token, _full_claims} = Guardian.encode_and_sign(device, :token, claims)
{:ok,
 "eyJhb...<skipped>...Zv3w",
 %{"aud" => "Device:db749ee8-1e9f-11e6-9d47-4b5e65de4b92", "exp" => 1464026216,
   "iat" => 1463767016, "iss" => "Issuer",
   "jti" => "294a5c14-f5e4-4b57-9f30-e6551825ccaf", "pem" => %{},
   "sub" => "Device:db749ee8-1e9f-11e6-9d47-4b5e65de4b92", "typ" => "token"}}
iex(10)> 
```

  As you can see it doesn't work. Is there a way to manually set TTL for a token available?

Thank you and best regards!

### PR DESCRIPTION
**Pull request by Hanspagh**
Fixes #153

### CODE REVIEW

**Comment by hassox** [comment]
I'm not sure that this will fix the issue. Looking at `lib/guardian/claims.ex` this is exactly what the `def ttl` function does right now. I think the ttl function needs to pattern match on the `"exp"` key.

**Comment by Hanspagh** [comment]
It works for the test I wrote.
The problem in claims is that 
`|> Guardian.Claims.ttl`
will [hit ](https://github.com/ueberauth/guardian/blob/master/lib/guardian/claims.ex#L80)
which resets the ttl to the default value

**Comment by hassox** [comment]
I took a look at this on my local machine. What do you think of https://github.com/ueberauth/guardian/compare/ttl-exp-fix

**Comment by Hanspagh** [comment]
Makes sense. The only problem I see is if someone does something like this
`claims = %{"exp" => exp, "iat" => iat} `

**Comment by Hanspagh** [comment]
Maybe you should merge your changes and I can close this?

**Comment by hassox** [comment]
Ok I've just made a PR for the other branch. If the tests all go green I'll merge.

**Pull request closed without merging**
