### PR TITLE
fix after_encode_and_sign dialyzer_error

### PR DESCRIPTION
**Pull request by ericsullivan**
Fixes https://github.com/ueberauth/guardian/issues/252

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @ericsullivan!  While we're updating the typespecs we don't we fix `after_sign_in/2`?  Based on the code here it does _not_ return a connection:

https://github.com/ueberauth/guardian/blob/9720eb6fc5278a9945f4235b0488f7480aeaa086/lib/guardian/plug.ex#L179-L184

**Comment by ericsullivan** [comment]
I put additional updates to the typespec in a different PR because dialyzer failed without this change, but wasn't complaining about the other code. Should "mix dialyzer" be added to travis.yml?

I think after_sign_in does return a conn. The default hook implementation returns conn and the api_sign_in also has a method signature that returns conn.

**Comment by doomspork** [comment]
@ericsullivan if you can rebase this to resolve the conflict I'd be happy to merge 👍

**Comment by ericsullivan** [comment]
https://github.com/ueberauth/guardian/pull/256 actually included this fix. Since that was merged first this is no longer needed.

**Pull request closed without merging**
